config/routes.rb
Rails.application.routes.draw do
  get 'products/new'

  get 'products/create'
  post 'products/create'
  get 'products/index'

  get 'products/:id' , to: "products#new_product_category", as: "new_product"
  post 'products/create_product_category'

  get 'categories/new'

  get 'categories/create'
  post 'categories/create'
  get 'categories/index'
  get 'categories/:id', to: "categories#show", as: 'categories'

  resources :registrations
  resources :books

  get 'employees/new'

  get 'employees/create'
  post 'employees/create'

  get 'employees/edit'

  get 'employees/index'

  get 'employees/:id' , to: "employees#show", as: "mobin"
  get 'employees/:id/edit', to: "employees#edit", as: "edit"
  patch 'employees/:id/update', to: "employees#update", as: "update"
  delete 'employees/:id/delete', to: "employees#delete", as: "delete"

  get 'mathematics/evenodd'
  post 'mathematics/evenodd'

  get 'mathematics/prime'
  post "mathematics/prime"

  get 'mathematics/palidrom'

  get 'calculaions/evenodd'
  post 'calculaions/evenodd'

  get 'calculaions/addition'
  post 'calculaions/addition'

  get 'attendence/new'

  get 'attendence/show'

  get 'attendence/edit'

  get 'attendence/delete'

  get 'attendence/update'

  get "students/show"
  post 'students/show'
  get "students/create"
  get "employees/new"

  get 'teachers/new'
  get 'classes/new'

   root 'employees#index'

end

app/models/book.rb
class Book < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :products
end

app/models/employee.rb
class Employee < ActiveRecord::Base
	#validates :name,:age,:salary,:gender, presence: true
	#validates :age ,  numericality: true
	#validates :name ,  length: { in: 6..20 }
	#validates :name , uniqueness: true
	#validates_format_of :email, :with => /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
	validate :phone_validate

	validate :age_limit

	def age_limit
		if self.age.to_i < 21 or self.age.to_i > 65
			errors.add(:age , "age should be between 21 to 65 years only")
		end
	end

	def phone_validate
		if self.phone.length != 10
			errors.add(:phone, "Phone number should be equal to 10 digits")
		end 
	end
end

app/models/product.rb
class Product < ActiveRecord::Base
	belongs_to :category
end

app/models/registration.rb
class Registration < ActiveRecord::Base
	before_save :username

	def username
		self.uname = "#{self.fname}  #{self.lname}"
	end
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:name, :author, :description, :year)
    end
end

app/controllers/classes_controller.rb
class ClassesController < ApplicationController
	def new
		@a = 10
		@b = 20
		@c = @a + @b
	end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_index_path
    else
      render 'new'
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end

  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to root_path
    end

  end

  def delete
    @employee = Employee.find(params[:id])
    if @employee.delete
      redirect_to root_path
    end
  end

  def show
    @employee = Employee.find(params[:id])
  end

  def index
    @employees = Employee.all
  end

private
  def employee_params
    params.require(:employee).permit(:name,:age,:salary,:gender,:email,:phone)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
  	@product = Product.new
  end

  def new_product_category
    @category = Category.find params[:id]
    @product = @category.products.new
  end

  def create_product_category
    @product = Product.new(product_params)
    if @product.save
      redirect_to products_index_path
    end
  end

  def create
  	@category = Category.find(params[:category])
  	@product = @category.products.new(product_params)
  	if @product.save
  		redirect_to products_index_path
  	end
  end

  def index
  	@products = Product.all
  end

  private
  def product_params
  	params.require(:product).permit!
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
	def show
		@name = params[:name]
		@age = params[:age]
		@gender = params[:gender]
		@address = params[:address]

		@s = Student.new(:name => @name, :age => @age, :gender => @gender, :address => @address)
		@s.save
	end
	def create
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attendence_helper.rb
module AttendenceHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/calculaions_helper.rb
module CalculaionsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/classes_helper.rb
module ClassesHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/mathematics_helper.rb
module MathematicsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/views/employees/create.html.erb
<%= @employee.name %>
<%= @employee.age %>

app/views/employees/delete.html.erb
<h1>Employees#delete</h1>
<p>Find me in app/views/employees/delete.html.erb</p>

app/views/employees/edit.html.erb
<h1>Employees#edit</h1>
<%=form_for @employee, url: update_path(@employee) do |f| %>
<p>Name: <%= f.text_field :name %> </p>
<p>Age: <%= f.number_field :age %></p>
<p>Saraly: <%= f.number_field :salary %></p>
<p>gender: <%= f.radio_button :gender, 'male' %> Male <%= f.radio_button :gender, 'female' %> FeMale </p>
<p><%= f.submit %></p>
<% end %>

app/views/employees/index.html.erb
<table border="10px" style="width:100%">
	<tr>
		<th>Name</th>
		<th>Age</th>
		<th>Salary</th>
		<th>Gender</th>
		<th>Email</th>
		<th>Phone</th>
		<th>Action</th>
	</tr>

<% @employees.each do |emp| %>
<tr>
<td><%= emp.name %></td>
<td><%= emp.age %></td>
<td><%= emp.salary %></td>
<td><%= emp.gender %></td>
<td><%= emp.email %></td>
<td><%= emp.phone %></td>
<td><%= link_to "show" ,mobin_path(emp) %> |
	<%= link_to "edit" ,edit_path(emp) %> |
	<%= link_to "delete" ,delete_path(emp), method: "delete" , data: {confirm: "Are you sure"}%></td>
<% end %>

</table>

app/views/employees/new.html.erb
<%= form_for @employee, url: {action: "create"} do |f| %>

<% if @employee.errors.any? %>
	<% @employee.errors.full_messages.each do |msg| %>
		<%= msg %><br />
	<% end %>
<% end %>


<p>Name: <%= f.text_field :name %> </p>
<p>Age: <%= f.number_field :age %></p>
<p>Saraly: <%= f.number_field :salary %></p>
<p>gender: <%= f.radio_button :gender, 'male' %> Male <%= f.radio_button :gender, 'female' %> FeMale </p>
<p>Email: <%= f.text_field :email %></p>
<p>Phone: <%= f.text_field :phone %></p>
<p><%= f.submit %></p>
<% end %>

app/views/employees/show.html.erb
<h1>Employees#show</h1>
<p>Name: <%= @employee.name %></p>
<p>Age: <%= @employee.age %></p>
<p>Salary: <%= @employee.salary %></p>
<p>Gender: <%= @employee.gender %></p>

app/views/employees/update.html.erb
<h1>Employees#update</h1>
<p>Find me in app/views/employees/update.html.erb</p>